﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace LaptopPricesGUI
{
    public partial class MLModelPredictPrice
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"CPU", @"CPU"),new InputOutputColumnPair(@"GPU", @"GPU"),new InputOutputColumnPair(@"RAMType", @"RAMType"),new InputOutputColumnPair(@"SSD", @"SSD")})      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"GHz", @"GHz"),new InputOutputColumnPair(@"RAM", @"RAM"),new InputOutputColumnPair(@"Screen", @"Screen"),new InputOutputColumnPair(@"Storage", @"Storage"),new InputOutputColumnPair(@"Weight", @"Weight")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"CPU",@"GPU",@"RAMType",@"SSD",@"GHz",@"RAM",@"Screen",@"Storage",@"Weight"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.FastTreeTweedie(new FastTreeTweedieTrainer.Options(){NumberOfLeaves=73,MinimumExampleCountPerLeaf=2,NumberOfTrees=22,MaximumBinCountPerFeature=8,LearningRate=0.000250180224056756F,FeatureFraction=0.853651734419188F,LabelColumnName=@"Price",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
